const {
  toStringValue,
  safeJsonParse,
  createTextBlock,
  createToolUseBlock,
  createToolResultBlock,
  normalizeAssistantBlocks,
  normalizeMessageBlocks,
  renderBlock,
  serializeBlocks,
  extractTextFromBlocks,
  toolUseBlocks,
} = require('./query/blocks.cjs');
const {
  stripAssistantWrappers,
  stripThinkingBlocks,
  parseAssistantResponse,
  extractStreamingToolCalls,
  flattenMessagesForModel,
  buildSystemPrompt,
  renderToolCatalog,
  normalizePromptToolDefinition,
} = require('./services/model/QwenAdapter.cjs');

module.exports = {
  toStringValue,
  safeJsonParse,
  createTextBlock,
  createToolUseBlock,
  createToolResultBlock,
  normalizeAssistantBlocks,
  normalizeMessageBlocks,
  renderBlock,
  serializeBlocks,
  extractTextFromBlocks,
  toolUseBlocks,
  stripAssistantWrappers,
  stripThinkingBlocks,
  parseAssistantResponse,
  extractStreamingToolCalls,
  flattenMessagesForModel,
  buildSystemPrompt,
  renderToolCatalog,
  normalizePromptToolDefinition,
};
