from typing import Dict, List

from ...utils.time import now_iso
from .methods_index import METHODS_INDEX_RELATIVE_PATH
from .wiki_runtime import _raw_source_root_text


def build_bootstrap_templates(wiki_id: str) -> List[Dict[str, str]]:
    today = now_iso()[:10]
    raw_source_text = _raw_source_root_text()
    return [
        {
            "path": "README.md",
            "kind": "readme",
            "content": "\n".join([
                "# LLM Wiki",
                "",
                f"This wiki compiles knowledge for `{wiki_id}` into persistent markdown pages.",
                "",
                "## Layers",
                "",
                f"- Canonical raw source root for runtime methods ingest and future curated ingest: `{raw_source_text}`.",
                "- Current answer mode is wiki-only: answer from pages already compiled into this wiki.",
                "- `raw/` keeps immutable source manifests and ingestion traces once ingest exists.",
                "- `pages/` keeps curated synthesis pages for topics, entities, analyses, and decisions.",
                f"- Structured symbol verification lives in `{METHODS_INDEX_RELATIVE_PATH}`.",
                "- `workflows/` keep verified task and implementation guidance.",
                "- When a workflow explanation needs to mention a desktop shell and none is specified, default to WPF.",
                "",
                "## Operations",
                "",
                "- Runtime methods ingest is active: raw sources are compiled into `.runtime/methods_index.json` during rebuild.",
                "- Query should use the wiki first and stay within curated wiki pages, using the runtime methods index only for symbol verification.",
                "- Lint should detect broken links, orphan pages, and uncited curated claims.",
            ]),
        },
        {
            "path": "SCHEMA.md",
            "kind": "schema",
            "content": "\n".join([
                "# LLM Wiki Schema",
                "",
                "## Canonical Structure",
                "",
                f"- Raw source root for runtime methods ingest and future curated ingest: `{raw_source_text}`.",
                "- `README.md`: human-readable overview of the wiki and its operating model.",
                "- `SCHEMA.md`: editing rules and directory conventions.",
                "- `index.md`: generated content-oriented catalog for navigation.",
                "- `log.md`: chronological append-only record of ingest, writeback, and lint events.",
                "- `pages/sources/raw-source-root.md`: canonical raw source root and ingest boundary.",
                "- `pages/decisions/current-answer-policy.md`: current answer contract for this project.",
                "- `pages/topics/todo-raw-source-ingest.md`, `pages/analyses/todo-compiled-wiki-growth.md`: TODO placeholders for future accumulation work.",
                "- `pages/home.md`: curated landing page for high-level orientation.",
                "- `pages/sources/`: source summary pages derived from raw sources.",
                "- `pages/topics/`: curated synthesis pages for recurring themes or features.",
                "- `pages/entities/`: entity-centric reference pages when named subjects matter.",
                "- `pages/analyses/`: saved query answers, comparisons, and deep dives.",
                "- `pages/decisions/`: decision records and notable tradeoffs.",
                "- `workflows/`: verified task or implementation workflows.",
                f"- `{METHODS_INDEX_RELATIVE_PATH}`: generated symbol verification index used by runtime lookup.",
                "",
                "## Editing Rules",
                "",
                "- Current answer mode is `wiki-only`: answer from pages that already exist in the active wiki.",
                "- Do not read directly from `raw_source/source` when answering questions.",
                "- Treat the raw source root as immutable ingest input and track remaining curated-ingest gaps with TODO pages.",
                "- Prefer updating curated pages under `pages/` and `workflows/` over editing generated runtime indices.",
                "- Every curated page should carry explicit provenance via `sources` frontmatter or inline source anchors.",
                "- `index.md` must be rebuilt after ingest, writeback, or major manual edits.",
                "- `log.md` must record ingest, writeback, lint, and repair events.",
                "- Keep relative markdown links stable.",
                "- If a workflow answer needs a desktop shell and the user did not ask for another stack, default to WPF.",
            ]),
        },
        {
            "path": "index.md",
            "kind": "index",
            "content": "\n".join([
                "# LLM Wiki Index",
                "",
                "- [SCHEMA.md](SCHEMA.md)",
                "- [log.md](log.md)",
                "- [pages/home.md](pages/home.md)",
                "",
                "## Curated Content",
                "",
                "- This file is generated. Rebuild it after ingest, writeback, or repair.",
                "- Current answer policy is wiki-only for curated pages; runtime methods ingest is active.",
                "- Workflow pages decide desktop shell defaults; use WPF unless a workflow or user request says otherwise.",
                "- Runtime symbol verification is stored outside the human-facing wiki in `.runtime/`.",
                "",
                "## Reference",
                "",
                "- [workflows/](workflows/) - verified workflow pages",
                f"- `{METHODS_INDEX_RELATIVE_PATH}` - generated runtime symbol index",
            ]),
        },
        {
            "path": "log.md",
            "kind": "log",
            "content": "\n".join([
                "# LLM Wiki Log",
                "",
                f"## [{today}] bootstrap | Initialize wiki structure",
                "",
                "- Created the coordination spine and baseline folders for wiki-first operation.",
                "- Declared wiki-first answering as the default mode until raw-source ingest exists.",
            ]),
        },
        {
            "path": "pages/home.md",
            "kind": "home",
            "content": "\n".join([
                "# Wiki Home",
                "",
                "Use this page for a curated overview of the knowledge base.",
                "",
                "## Start Here",
                "",
                "- Review [index.md](../index.md) for the current catalog.",
                "- Review [SCHEMA.md](../SCHEMA.md) before changing page structure.",
                "- Use `pages/topics/`, `pages/entities/`, `pages/analyses/`, and `pages/decisions/` for curated synthesis.",
                f"- Current answer mode is wiki-only; raw source root is `{raw_source_text}`.",
                "- Review [pages/decisions/current-answer-policy.md](../pages/decisions/current-answer-policy.md) for the active answer contract.",
                "- Review [pages/sources/raw-source-root.md](../pages/sources/raw-source-root.md) for the ingest boundary.",
                "- Review [pages/topics/todo-raw-source-ingest.md](../pages/topics/todo-raw-source-ingest.md) for remaining curated ingest work.",
                "- For desktop-oriented workflows, default to WPF unless the user explicitly asks for another shell.",
            ]),
        },
        {
            "path": "pages/sources/raw-source-root.md",
            "kind": "source",
            "content": "\n".join([
                "---",
                "title: Raw Source Root",
                "description: Canonical immutable raw source tree used for runtime symbol ingest and future curated ingest work.",
                "tags:",
                "  - source",
                "  - raw",
                "  - todo",
                "---",
                "",
                "# Raw Source Root",
                "",
                "## Current Role",
                f"- Canonical raw source tree: `{raw_source_text}`",
                "- This path is the immutable source-of-truth root for future accumulation work.",
                "- Current answers must not read this tree directly. For now, responses are grounded only in the `engine` wiki.",
                "",
                "## TODO",
                "- Define source filtering rules.",
                "- Define source manifests or summaries per module.",
                "- Define the ingest pass that compiles raw source changes into curated wiki pages.",
            ]),
        },
        {
            "path": "pages/topics/todo-raw-source-ingest.md",
            "kind": "topic",
            "content": "\n".join([
                "---",
                "title: TODO | Raw Source Ingest",
                "description: Remaining work for extending raw-source ingest beyond the runtime methods index.",
                "tags:",
                "  - todo",
                "  - topic",
                "  - ingest",
                "sources:",
                "  - pages/sources/raw-source-root.md",
                "---",
                "",
                "# TODO | Raw Source Ingest",
                "",
                "## Current State",
                f"- Raw source root is fixed at `{raw_source_text}`.",
                "- The current system answers from the `engine` wiki only.",
                "- There is now an active ingest pass that reads raw sources and rebuilds `.runtime/methods_index.json` automatically.",
                "- Curated pages and workflows are still maintained separately and are not regenerated from raw sources yet.",
                "",
                "## TODO Checklist",
                "- Define source filtering rules.",
                "- Define ingest cadence and trigger conditions.",
                "- Define contradiction/supersession recording.",
                "- Define which curated page families update per ingest.",
            ]),
        },
        {
            "path": "pages/analyses/todo-compiled-wiki-growth.md",
            "kind": "analysis",
            "content": "\n".join([
                "---",
                "title: TODO | Compiled Wiki Growth",
                "description: Placeholder for the gap between current wiki-only answers and future accumulation.",
                "tags:",
                "  - todo",
                "  - analysis",
                "  - llm-wiki",
                "sources:",
                "  - pages/sources/raw-source-root.md",
                "  - pages/topics/todo-raw-source-ingest.md",
                "---",
                "",
                "# TODO | Compiled Wiki Growth",
                "",
                "## Current Constraint",
                "- The system already uses the wiki as the answer layer.",
                "- It now uses raw sources to rebuild the runtime methods index, but not yet to refresh curated pages and workflows.",
                "- This means the wiki is useful now, but not yet compounding in the LLM Wiki sense.",
            ]),
        },
        {
            "path": "pages/decisions/current-answer-policy.md",
            "kind": "decision",
            "content": "\n".join([
                "---",
                "title: Current Answer Policy",
                "description: Current operating contract for engine answers with raw-source symbol ingest enabled and curated ingest still pending.",
                "tags:",
                "  - decision",
                "  - policy",
                "  - wiki-only",
                "sources:",
                "  - README.md",
                "  - SCHEMA.md",
                "  - pages/sources/raw-source-root.md",
                "---",
                "",
                "# Current Answer Policy",
                "",
                "## Decision",
                "- Engine answers are currently grounded only in the `engine` wiki.",
                f"- The raw source tree at `{raw_source_text}` is not used directly for answer generation.",
                "",
                "## Consequence",
                "- If the wiki does not contain enough information, expose the gap instead of silently grounding on raw source code.",
                "- The wiki remains the explicit answer boundary until curated ingest is implemented.",
            ]),
        },
    ]


__all__ = ["build_bootstrap_templates"]
